/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udb.sv.vista;

import com.udb.sv.conexion.Conexion;
import com.udb.sv.conexion.Consultas;
import com.udb.sv.conexion.Equipos;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.ooxml.JRDocxExporter;
import net.sf.jasperreports.engine.export.ooxml.JRXlsxExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;
import net.sf.jasperreports.export.SimpleXlsxReportConfiguration;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rigoberto
 */
public class CreacionReportes extends javax.swing.JFrame {

    /**
     * Creates new form CreacionReportes
     */
    public CreacionReportes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        btngenerar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbEquipos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnWord = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnWord2 = new javax.swing.JButton();
        btnExcel2 = new javax.swing.JButton();
        cmbEquipos2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        jLabel1.setText("Generar reporte equipos");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btngenerar2.setText("Generar");
        btngenerar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerar2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Generar reporte de los jugadores de cada equipo");

        cmbEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbEquiposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnGenerar)
                            .addComponent(jLabel2))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btngenerar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngenerar2)
                    .addComponent(cmbEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes PDF", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        btnWord.setText("Word");
        btnWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordActionPerformed(evt);
            }
        });

        btnExcel.setText("Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        jLabel3.setText("Exportar reporte de equipos a");

        jLabel4.setText("Exportar reporte de jugadores a");

        btnWord2.setText("Word");
        btnWord2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWord2ActionPerformed(evt);
            }
        });

        btnExcel2.setText("Excel");
        btnExcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel2ActionPerformed(evt);
            }
        });

        cmbEquipos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEquipos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnWord)
                        .addGap(62, 62, 62)
                        .addComponent(btnExcel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnWord2)
                                .addGap(57, 57, 57)
                                .addComponent(btnExcel2))
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addComponent(cmbEquipos2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWord)
                    .addComponent(btnExcel))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWord2)
                    .addComponent(btnExcel2)
                    .addComponent(cmbEquipos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exportar reporte", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reportes parametrizados", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {          
            Conexion con = new Conexion();
            Connection conn = con.getConn();
            
            JasperReport resporte = null;
            String path = "src/main/java/com/udb/sv/reportes/Equipos.jasper";
            
            resporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(resporte, null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(CreacionReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Consultas obj = new Consultas();
        DefaultComboBoxModel<Equipos> model = new DefaultComboBoxModel<>();
        List<Equipos> list = obj.llenarCombo();
        for(Equipos temp : list){
            model.addElement(temp);
        }
        cmbEquipos.setModel(model);
        cmbEquipos2.setModel(model);
    }//GEN-LAST:event_formWindowOpened

    private void cmbEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbEquiposMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbEquiposMouseClicked

    private void btngenerar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerar2ActionPerformed
        // TODO add your handling code here:
        int id = obtId();
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConn();
            
            JasperReport resporte = null;
            String path = "src/main/java/com/udb/sv/reportes/Jugadores_por_equipo.jasper";
            
            Map parametro = new HashMap();
            parametro.put("id_equi", id);
            
            resporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(resporte, parametro, conn);
            
            
            JasperViewer view = new JasperViewer(jprint, false);
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(CreacionReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btngenerar2ActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConn();
            
            JasperReport reporte = (JasperReport) JRLoader.loadObject(new File("/home/rigoberto/NetBeansProjects/reportes/src/main/java/com/udb/sv/reportes/Equipos.jasper"));
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);
            
            JRXlsxExporter exporter = new JRXlsxExporter();
            exporter.setExporterInput(new SimpleExporterInput(jprint));
            exporter.setExporterOutput(new SimpleOutputStreamExporterOutput(new File("/home/rigoberto/Equipos.xlsx")));
            SimpleXlsxReportConfiguration config = new SimpleXlsxReportConfiguration();
            config.setDetectCellType(true);
            config.setCollapseRowSpan(false);
            exporter.setConfiguration(config);
            exporter.exportReport();
            JOptionPane.showMessageDialog(null, "Reporte creado satisfactoriamente");
            
        } catch (Exception e) {
            Logger.getLogger(CreacionReportes.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordActionPerformed
        Conexion con = new Conexion();
        Connection conn = con.getConn();
            
        JasperReport reporte;
        try {
            reporte = (JasperReport) JRLoader.loadObject(new File("/home/rigoberto/NetBeansProjects/reportes/src/main/java/com/udb/sv/reportes/Equipos.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn); 
            
            JRDocxExporter exportar = new JRDocxExporter();
            exportar.setExporterInput(new SimpleExporterInput(jprint));
            File exportReportFile = new File("/home/rigoberto/Equipos.docx");
            exportar.setExporterOutput(new SimpleOutputStreamExporterOutput(exportReportFile));
            exportar.exportReport();
            JOptionPane.showMessageDialog(null, "Reporte creado satisfactoriamente");
        } catch (JRException ex) {
            Logger.getLogger(CreacionReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_btnWordActionPerformed

    private void cmbEquipos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEquipos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEquipos2ActionPerformed

    private void btnExcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel2ActionPerformed
        int id = obtId();
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConn();
            
            JasperReport reporte = (JasperReport) JRLoader.loadObject(new File("/home/rigoberto/NetBeansProjects/reportes/src/main/java/com/udb/sv/reportes/Jugadores_por_equipo.jasper"));
            
            Map parametro = new HashMap();
            parametro.put("id_equi", id);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, conn);
            
            JRXlsxExporter exporter = new JRXlsxExporter();
            exporter.setExporterInput(new SimpleExporterInput(jprint));
            exporter.setExporterOutput(new SimpleOutputStreamExporterOutput(new File("/home/rigoberto/Jugadores_por_equipo.xlsx")));
            SimpleXlsxReportConfiguration config = new SimpleXlsxReportConfiguration();
            config.setDetectCellType(true);
            config.setCollapseRowSpan(false);
            exporter.setConfiguration(config);
            exporter.exportReport();
            JOptionPane.showMessageDialog(null, "Reporte creado satisfactoriamente");
        } catch (Exception e) {
            Logger.getLogger(CreacionReportes.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnExcel2ActionPerformed

    private void btnWord2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWord2ActionPerformed
        int id = obtId();
        try {
            Conexion con = new Conexion();
            Connection conn = con.getConn();
            
            JasperReport reporte = (JasperReport) JRLoader.loadObject(new File("/home/rigoberto/NetBeansProjects/reportes/src/main/java/com/udb/sv/reportes/Jugadores_por_equipo.jasper"));
            
            Map parametro = new HashMap();
            parametro.put("id_equi", id);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, conn);
            
            JRDocxExporter exportar = new JRDocxExporter();
            exportar.setExporterInput(new SimpleExporterInput(jprint));
            File exportReportFile = new File("/home/rigoberto/Jugadores_por_equipo.docx");
            exportar.setExporterOutput(new SimpleOutputStreamExporterOutput(exportReportFile));
            exportar.exportReport();
            JOptionPane.showMessageDialog(null, "Reporte creado satisfactoriamente");
        }catch(Exception e){
            Logger.getLogger(CreacionReportes.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnWord2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionReportes().setVisible(true);
            }
        });
    }
    
    private int obtId(){
        int id = ((Equipos)(cmbEquipos.getSelectedItem())).getCodiEqui();
        
        System.err.println(id);
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnExcel2;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnWord;
    private javax.swing.JButton btnWord2;
    private javax.swing.JButton btngenerar2;
    private javax.swing.JComboBox<Equipos> cmbEquipos;
    private javax.swing.JComboBox<Equipos> cmbEquipos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
